//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#include "gctrl.hpp"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdexcept>
#include <cerrno>

namespace gctrl {
    namespace udp {
        void signal_registry::subscribe(uint64_t id, signal_callback callback) {
            std::lock_guard<std::mutex> lock(mutex_);
            registry_[id] = callback;
        }

        void signal_registry::notify(uint64_t id, const std::vector<uint8_t>& data) {
            std::lock_guard<std::mutex> lock(mutex_);
            if (registry_.count(id)) {
                registry_[id](data);
            }
        }

        listener::listener(const std::string& address, uint16_t port, signal_registry& registry)
            : registry_(registry), stop_(false), socket_fd_(-1) {
            initialize_socket(address, port);
        }

        listener::~listener() {
            stop();
        }

        void listener::start() {
            listener_thread_ = std::thread([this]() { listen_for_packets(); });
        }

        void listener::stop() {
            if (!stop_) {
                stop_ = true;
                close_socket();
                if (listener_thread_.joinable()) {
                    listener_thread_.join();
                }
            }
        }

        void listener::initialize_socket(const std::string& address, uint16_t port) {
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (socket_fd_ < 0) {
                throw std::runtime_error("Socket creation failed");
            }

            int flags = fcntl(socket_fd_, F_GETFL, 0);
            if (flags < 0 || fcntl(socket_fd_, F_SETFL, flags | O_NONBLOCK) < 0) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port);
            server_addr.sin_addr.s_addr = INADDR_ANY;
            if (bind(socket_fd_, reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr)) < 0) {
                std::cerr << "Socket bind failed: " << strerror(errno) << std::endl;
                throw std::runtime_error("Socket bind failed");
            }
        }

        void listener::listen_for_packets() {
            while (!stop_) {
                std::vector<uint8_t> buffer(1024);
                sockaddr_in sender_addr{};
                socklen_t sender_addr_len = sizeof(sender_addr);
                ssize_t received_bytes = recvfrom(socket_fd_, buffer.data(), buffer.size(), 0,
                    reinterpret_cast<sockaddr*>(&sender_addr), &sender_addr_len);
                if (received_bytes > 0) {
                    buffer.resize(received_bytes);
                    if (buffer.size() >= sizeof(uint64_t)) {
                        uint64_t id;
                        std::memcpy(&id, buffer.data(), sizeof(uint64_t));
                        registry_.notify(id, { buffer.begin() + sizeof(uint64_t), buffer.end() });
                    }
                }
                else if (received_bytes < 0 && errno != EAGAIN && errno != EWOULDBLOCK) {
                    std::cerr << "recvfrom error: " << strerror(errno) << std::endl;
                }

                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        }

        void listener::close_socket() {
            if (socket_fd_ >= 0) {
                close(socket_fd_);
                socket_fd_ = -1;
            }
        }

        sender::sender(const std::string& address, uint16_t port)
            : address_(address), port_(port), socket_fd_(-1) {
            initialize_socket();
        }

        void sender::initialize_socket() {
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (socket_fd_ < 0) {
                throw std::runtime_error("Socket creation failed");
            }

            int flags = fcntl(socket_fd_, F_GETFL, 0);
            if (flags < 0 || fcntl(socket_fd_, F_SETFL, flags | O_NONBLOCK) < 0) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }
        }

        void sender::send(uint64_t id, const std::vector<uint8_t>& data) {
            std::vector<uint8_t> packet(sizeof(id) + data.size());
            std::memcpy(packet.data(), &id, sizeof(id));
            std::memcpy(packet.data() + sizeof(id), data.data(), data.size());

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port_);
            inet_pton(AF_INET, address_.c_str(), &server_addr.sin_addr);

            ssize_t result = sendto(socket_fd_, packet.data(), packet.size(), 0,
                reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr));
            if (result < 0 && errno != EAGAIN && errno != EWOULDBLOCK) {
                std::cerr << "sendto error: " << strerror(errno) << std::endl;
            }
        }

        void sender::close_socket() {
            if (socket_fd_ >= 0) {
                close(socket_fd_);
                socket_fd_ = -1;
            }
        }

        sender::~sender() {
            close_socket();
        }
    }
}
