//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once
#include <controller/thermal_controller.hpp>
#include <controller/humidity_controller.hpp>
#include <driver/udp.hpp>
namespace machine {
    struct thermostat {
    public:
        controller::thermal_controller thermostat;
        controller::humidity_controller humidity_controller;
        driver::udp machine_driver;
        void at_1hz(float timestep) {
            thermostat.socket_to_ctrl2.incoming = humidity_controller.plug_from_ctrl1.outgoing;
            thermostat.plug_to_driver.incoming = machine_driver.socket.outgoing;
            thermostat.debug_port.incoming = machine_driver.debug.outgoing;
            thermostat.at_1hz(timestep);
            humidity_controller.plug_from_ctrl1.incoming = thermostat.socket_to_ctrl2.outgoing;
            humidity_controller.at_1hz(timestep);
        }
        void at_10hz(float timestep) {
            thermostat.socket_to_ctrl2.incoming = humidity_controller.plug_from_ctrl1.outgoing;
            thermostat.plug_to_driver.incoming = machine_driver.socket.outgoing;
            thermostat.debug_port.incoming = machine_driver.debug.outgoing;
            thermostat.at_10hz(timestep);
            humidity_controller.plug_from_ctrl1.incoming = thermostat.socket_to_ctrl2.outgoing;
            humidity_controller.at_10hz(timestep);
        }
        void at_100hz(float timestep) {
            thermostat.socket_to_ctrl2.incoming = humidity_controller.plug_from_ctrl1.outgoing;
            thermostat.plug_to_driver.incoming = machine_driver.socket.outgoing;
            thermostat.debug_port.incoming = machine_driver.debug.outgoing;
            thermostat.at_100hz(timestep);
            humidity_controller.plug_from_ctrl1.incoming = thermostat.socket_to_ctrl2.outgoing;
            humidity_controller.at_100hz(timestep);
        }
        void at_1khz(float timestep) {
            thermostat.socket_to_ctrl2.incoming = humidity_controller.plug_from_ctrl1.outgoing;
            thermostat.plug_to_driver.incoming = machine_driver.socket.outgoing;
            thermostat.debug_port.incoming = machine_driver.debug.outgoing;
            thermostat.at_1khz(timestep);
            humidity_controller.plug_from_ctrl1.incoming = thermostat.socket_to_ctrl2.outgoing;
            humidity_controller.at_1khz(timestep);
            machine_driver.socket.incoming = thermostat.plug_to_driver.outgoing;
            machine_driver.debug.incoming = thermostat.debug_port.outgoing;
            machine_driver.at_1khz(timestep);
        }
        void at_10khz(float timestep) {
            thermostat.socket_to_ctrl2.incoming = humidity_controller.plug_from_ctrl1.outgoing;
            thermostat.plug_to_driver.incoming = machine_driver.socket.outgoing;
            thermostat.debug_port.incoming = machine_driver.debug.outgoing;
            thermostat.at_10khz(timestep);
            humidity_controller.plug_from_ctrl1.incoming = thermostat.socket_to_ctrl2.outgoing;
            humidity_controller.at_10khz(timestep);
        }
    };
}
