//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once
#include <function/logistic.hpp>
namespace element {
    struct humidity_regulator {
    public:
        struct input_type {
            float setpoint;
            float humidity;
        } in;
        struct output_type {
            float command;
        } out;
        struct memory_type {
            float error;
            float c;
        } mem;
        function::logistic logistic;
        void at_1khz(float timestep) {
            
            logistic.in.x = mem.error = in.setpoint - in.humidity;
            logistic();
            out.command = logistic.out.control_signal * max(0.0f, mem.error);
            
        }
    };
}
