//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once
#include <port/thermostat_socket.hpp>
#include <port/debug_socket.hpp>
namespace driver {
    struct udp {
    private:
        gctrl::udp::signal_registry registry;
        gctrl::udp::listener listener;
        gctrl::udp::sender sender;
    public:
        port::socket::thermostat socket;
        port::socket::debug debug;
        udp() : listener("127.0.0.1", 8081, registry), sender("127.0.0.1", 8080) {
            listener.start();
            // incoming data from udp device:
            registry.subscribe(254913821784062, [&](const std::vector<uint8_t>& data) {
                socket.outgoing.temprature = gctrl::binary::deserialize<float>(data);
            });
            registry.subscribe(254910584829948, [&](const std::vector<uint8_t>& data) {
                socket.outgoing.humidity = gctrl::binary::deserialize<float>(data);
            });
            registry.subscribe(272231652384767, [&](const std::vector<uint8_t>& data) {
                socket.outgoing.user_desired_temprature = gctrl::binary::deserialize<float>(data);
            });
            registry.subscribe(113888555931646, [&](const std::vector<uint8_t>& data) {
                socket.outgoing.user_desired_humidity = gctrl::binary::deserialize<float>(data);
            });
        }
        void at_1khz(float timestep) {
            // send socket data incoming from the controllers
            sender.send(114304630104062, gctrl::binary::serialize(socket.incoming.heating));
            sender.send(131494171088894, gctrl::binary::serialize(socket.incoming.cooling));
            sender.send(272532827271164, gctrl::binary::serialize(socket.incoming.humidfying));
            // send socket data incoming from the controllers
            sender.send(281397207956378, gctrl::binary::serialize(debug.incoming.timestep));
            sender.send(79057173512158, gctrl::binary::serialize(debug.incoming.time));
        }
    };
}

