//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once
#include <element/humidity_regulator.hpp>
#include <element/low_pass_filter.hpp>
#include <port/humidostat_plug.hpp>
namespace controller {
    struct humidity_controller {
    private:
        element::humidity_regulator hr;
        element::low_pass_filter lpf;
    public:
        port::plug::humidostat plug_from_ctrl1;
        void at_1hz(float timestep) {
            plug_from_ctrl1.outgoing.humidifying = lpf.out.filtered;
        }
        void at_10hz(float timestep) {
            plug_from_ctrl1.outgoing.humidifying = lpf.out.filtered;
        }
        void at_100hz(float timestep) {
            plug_from_ctrl1.outgoing.humidifying = lpf.out.filtered;
        }
        void at_1khz(float timestep) {
            hr.in.setpoint = plug_from_ctrl1.incoming.user_desired_humidity;
            hr.in.humidity = plug_from_ctrl1.incoming.humidity;
            hr.at_1khz(timestep);
            lpf.in.current_value = hr.out.command;
            lpf.at_1khz(timestep);
            plug_from_ctrl1.outgoing.humidifying = lpf.out.filtered;
        }
        void at_10khz(float timestep) {
            plug_from_ctrl1.outgoing.humidifying = lpf.out.filtered;
        }
    };
}
