//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once
#include <element/thermal_regulator.hpp>
#include <element/low_pass_filter.hpp>
#include <element/debug.hpp>
#include <port/thermostat_plug.hpp>
#include <port/debug_plug.hpp>
#include <port/humidostat_socket.hpp>
namespace controller {
    struct thermal_controller {
    private:
        element::thermal_regulator thermal_regulator_element;
        element::low_pass_filter lpfc;
        element::low_pass_filter lpfh;
        element::debug debug_element;
    public:
        port::plug::thermostat plug_to_driver;
        port::plug::debug debug_port;
        port::socket::humidostat socket_to_ctrl2;
        void at_1hz(float timestep) {
            plug_to_driver.outgoing.heating = thermal_regulator_element.out.heating;
            plug_to_driver.outgoing.cooling = lpfc.out.filtered;
            plug_to_driver.outgoing.humidfying = socket_to_ctrl2.incoming.humidifying;
            debug_port.outgoing.timestep = debug_element.out.timestep;
            debug_port.outgoing.time = debug_element.out.time;
            socket_to_ctrl2.outgoing.humidity = plug_to_driver.incoming.humidity;
            socket_to_ctrl2.outgoing.user_desired_humidity = plug_to_driver.incoming.user_desired_humidity;
        }
        void at_10hz(float timestep) {
            plug_to_driver.outgoing.heating = thermal_regulator_element.out.heating;
            plug_to_driver.outgoing.cooling = lpfc.out.filtered;
            plug_to_driver.outgoing.humidfying = socket_to_ctrl2.incoming.humidifying;
            debug_port.outgoing.timestep = debug_element.out.timestep;
            debug_port.outgoing.time = debug_element.out.time;
            socket_to_ctrl2.outgoing.humidity = plug_to_driver.incoming.humidity;
            socket_to_ctrl2.outgoing.user_desired_humidity = plug_to_driver.incoming.user_desired_humidity;
        }
        void at_100hz(float timestep) {
            plug_to_driver.outgoing.heating = thermal_regulator_element.out.heating;
            plug_to_driver.outgoing.cooling = lpfc.out.filtered;
            plug_to_driver.outgoing.humidfying = socket_to_ctrl2.incoming.humidifying;
            debug_port.outgoing.timestep = debug_element.out.timestep;
            debug_port.outgoing.time = debug_element.out.time;
            socket_to_ctrl2.outgoing.humidity = plug_to_driver.incoming.humidity;
            socket_to_ctrl2.outgoing.user_desired_humidity = plug_to_driver.incoming.user_desired_humidity;
        }
        void at_1khz(float timestep) {
            thermal_regulator_element.in.setpoint = plug_to_driver.incoming.user_desired_temprature;
            thermal_regulator_element.in.temprature = plug_to_driver.incoming.temprature;
            thermal_regulator_element.at_1khz(timestep);
            lpfc.in.current_value = thermal_regulator_element.out.cooling;
            lpfc.at_1khz(timestep);
            lpfh.in.current_value = thermal_regulator_element.out.heating;
            lpfh.at_1khz(timestep);
            debug_element.at_1khz(timestep);
            plug_to_driver.outgoing.heating = thermal_regulator_element.out.heating;
            plug_to_driver.outgoing.cooling = lpfc.out.filtered;
            plug_to_driver.outgoing.humidfying = socket_to_ctrl2.incoming.humidifying;
            debug_port.outgoing.timestep = debug_element.out.timestep;
            debug_port.outgoing.time = debug_element.out.time;
            socket_to_ctrl2.outgoing.humidity = plug_to_driver.incoming.humidity;
            socket_to_ctrl2.outgoing.user_desired_humidity = plug_to_driver.incoming.user_desired_humidity;
        }
        void at_10khz(float timestep) {
            plug_to_driver.outgoing.heating = thermal_regulator_element.out.heating;
            plug_to_driver.outgoing.cooling = lpfc.out.filtered;
            plug_to_driver.outgoing.humidfying = socket_to_ctrl2.incoming.humidifying;
            debug_port.outgoing.timestep = debug_element.out.timestep;
            debug_port.outgoing.time = debug_element.out.time;
            socket_to_ctrl2.outgoing.humidity = plug_to_driver.incoming.humidity;
            socket_to_ctrl2.outgoing.user_desired_humidity = plug_to_driver.incoming.user_desired_humidity;
        }
    };
}
