//
// General Controls Engine
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once

#include <string>
#include <sstream>
#include <filesystem>
#include <system_error>
#include <fstream>
#include <set>
#include <regex>
#include "templates.hpp"

namespace code {

    struct stream {
    private:
        std::stringstream output_stream;
        int indent_level = 0;
        const std::string indent_string = "    ";
        std::set<std::string> included_files;

    public:
        stream& reset() {
            output_stream.str(std::string());
            indent_level = 0;
            included_files.clear();
            return *this;
        }

        stream& indent() {
            for (int i = 0; i < indent_level; ++i) {
                output_stream << indent_string;
            }
            return *this;
        }

        stream& begin(const std::string& name) {
            reset();
            output_stream << "//\n";
            output_stream << "// Generated by General Controls Engine.\n";
            output_stream << "// License: GNU General Public License v3.0 or later.\n";
            output_stream << "//\n";
            output_stream << "// Copyright (C) 2024 Daher Alfawares\n";
            output_stream << "//\n";
            output_stream << "// This program is free software: you can redistribute it and/or modify\n";
            output_stream << "// it under the terms of the GNU General Public License as published by\n";
            output_stream << "// the Free Software Foundation, either version 3 of the License, or\n";
            output_stream << "// (at your option) any later version.\n";
            output_stream << "//\n";
            output_stream << "// This program is distributed in the hope that it will be useful,\n";
            output_stream << "// but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
            output_stream << "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n";
            output_stream << "// GNU General Public License for more details.\n";
            output_stream << "//\n";
            output_stream << "// You should have received a copy of the GNU General Public License\n";
            output_stream << "// along with this program. If not, see <https://www.gnu.org/licenses/>.\n";
            output_stream << "//\n";
            output_stream << "// Contact Information: www.gctrl.org\n";
            output_stream << "//\n\n";
            output_stream << "#pragma once" << "\n";
            return *this;
        }

        stream& end() {
            output_stream << "\n";
            return *this;
        }

        stream& include(const std::string& path) {
            if (included_files.insert(path).second) {
                output_stream << "#include <" << path << ">\n";
            }
            return *this;
        }

        stream& namespace_begin(const std::string& name) {
            indent();
            output_stream << "namespace " << name << " {\n";
            ++indent_level;
            return *this;
        }

        stream& namespace_end() {
            --indent_level;
            indent();
            output_stream << "}\n";
            return *this;
        }

        stream& struct_begin(const std::string& struct_name) {
            indent();
            output_stream << "struct " << struct_name << " {\n";
            ++indent_level;
            return *this;
        }

        stream& struct_end(const std::string& variable_name) {
            --indent_level;
            indent();
            output_stream << "}";
            if (!variable_name.empty()) {
                output_stream << " " << variable_name;
            }
            output_stream << ";\n";
            return *this;
        }

        stream& public_() {
            --indent_level;
            indent();
            output_stream << "public:\n";
            ++indent_level;
            return *this;
        }

        stream& private_() {
            --indent_level;
            indent();
            output_stream << "private:\n";
            ++indent_level;
            return *this;
        }

        stream& line(const std::string& string) {
            indent();
            output_stream << string << "\n";
            return *this;
        }

        stream& declare_variable(const std::string& type, const std::string& name, const std::string& value = "") {
            indent();
            output_stream << type << " " << name;
            if (!value.empty()) {
                output_stream << " = " << value;
            }
            output_stream << ";\n";
            return *this;
        }

        stream& function_begin(const std::string& signature) {
            indent();
            output_stream << signature << " {\n";
            ++indent_level;
            return *this;
        }

        stream& function_end() {
            --indent_level;
            indent();
            output_stream << "}\n";
            return *this;
        }

        stream& block(const std::string& code_block) {
            std::istringstream code_stream(code_block);
            std::string line;
            while (std::getline(code_stream, line)) {
                indent();
                output_stream << line << "\n";
            }
            return *this;
        }

        std::string string() const {
            return output_stream.str();
        }

        void commit(const std::string& path) {
            std::string prefixed_path = "gctrl/" + path;
            std::filesystem::create_directories(std::filesystem::path(prefixed_path).parent_path());
            std::ofstream file(prefixed_path);
            file << output_stream.str();
            file.close();
        }
    };

    static stream code_stream;

    inline void begin(const std::string& name) {
        ui::cout << name << ui::endl;
        code_stream.begin(name);
    }

    inline void end() {
        code_stream.end();
    }

    inline void include(const std::string& path) {
        code_stream.include(path);
    }

    inline void namespace_begin(const std::string& name) {
        code_stream.namespace_begin(name);
    }

    inline void namespace_end() {
        code_stream.namespace_end();
    }

    inline void struct_begin(const std::string& struct_name) {
        code_stream.struct_begin(struct_name);
    }

    inline void struct_end(const std::string& variable_name = "") {
        code_stream.struct_end(variable_name);
    }

    inline void public_() {
        code_stream.public_();
    }

    inline void private_() {
        code_stream.private_();
    }

    inline void declare_variable(const std::string& type, const std::string& name, const std::string& value = "") {
        code_stream.declare_variable(type, name, value);
    }

    inline void line(const std::string& line) {
        code_stream.line(line);
    }

    inline void function_begin(const std::string& signature) {
        code_stream.function_begin(signature);
    }

    inline void function_end() {
        code_stream.function_end();
    }

    inline void block(const std::string& code_block) {
        code_stream.block(code_block);
    }

    inline std::string string() {
        return code_stream.string();
    }

    inline void commit(const std::string& path) {
        code_stream.commit(path);
    }

    void delete_gctrl_directory() {
        std::filesystem::path directory = "gctrl";
        if (std::filesystem::exists(directory)) {
            try {
                std::filesystem::remove_all(directory);
                std::cout << "Successfully removed directory: " << directory << std::endl;
            }
            catch (const std::filesystem::filesystem_error& e) {
                std::cerr << "Error removing directory: " << directory << std::endl;
                std::cerr << "Reason: " << e.what() << std::endl;
            }
            catch (const std::exception& e) {
                std::cerr << "Unexpected error: " << e.what() << std::endl;
            }
        }
    }

    inline void generate_gctrl_header() {
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl.hpp");
        file << templates::gctrl_hpp;
        file.close();
        ui::cout << "gctrl.hpp" << ui::endl;
    }

    inline void generate_udp_driver_windows() {
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl_udp_windows.cpp");
        file << templates::gctrl_udp_windows_cpp;
        file.close();
        ui::cout << "gctrl_udp_windows.cpp" << ui::endl;
    }

    inline void generate_udp_driver_linux() {
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl_udp_linux.cpp");
        file << templates::gctrl_udp_linux_cpp;
        file.close();
        ui::cout << "gctrl_udp_linux.cpp" << ui::endl;
    }

    inline void generate_cmake(const std::string& machine_name) {
        std::string content = templates::cmake_lists_template;
        // Replace ${MACHINE_NAME} placeholder with actual machine name
        content = std::regex_replace(content, std::regex(R"(\$\{MACHINE_NAME\})"), machine_name);

        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/CMakeLists.txt");
        file << content;
        file.close();
        ui::cout << "CMakeLists.txt" << ui::endl;
    }

    inline void generate_boilerplate(const std::string& machine_name) {
        generate_gctrl_header();
        generate_udp_driver_windows();
        generate_udp_driver_linux();
        generate_cmake(machine_name);
    }
}
