//
// General Controls Engine
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once

#include <string>
#include <sstream>
#include <filesystem>
#include <system_error>
#include <fstream>
#include <set>

namespace code {

    struct stream {
    private:
        std::stringstream output_stream;
        int indent_level = 0;
        const std::string indent_string = "    ";
        std::set<std::string> included_files;

    public:
        stream& reset() {
            output_stream.str(std::string());
            indent_level = 0;
            included_files.clear();
            return *this;
        }

        stream& indent() {
            for (int i = 0; i < indent_level; ++i) {
                output_stream << indent_string;
            }
            return *this;
        }

        stream& begin(const std::string& name) {
            reset();
            output_stream << "//\n";
            output_stream << "// Generated by General Controls Engine.\n";
            output_stream << "// License: GNU General Public License v3.0 or later.\n";
            output_stream << "//\n";
            output_stream << "// Copyright (C) 2024 Daher Alfawares\n";
            output_stream << "//\n";
            output_stream << "// This program is free software: you can redistribute it and/or modify\n";
            output_stream << "// it under the terms of the GNU General Public License as published by\n";
            output_stream << "// the Free Software Foundation, either version 3 of the License, or\n";
            output_stream << "// (at your option) any later version.\n";
            output_stream << "//\n";
            output_stream << "// This program is distributed in the hope that it will be useful,\n";
            output_stream << "// but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
            output_stream << "// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n";
            output_stream << "// GNU General Public License for more details.\n";
            output_stream << "//\n";
            output_stream << "// You should have received a copy of the GNU General Public License\n";
            output_stream << "// along with this program. If not, see <https://www.gnu.org/licenses/>.\n";
            output_stream << "//\n";
            output_stream << "// Contact Information: www.gctrl.org\n";
            output_stream << "//\n\n";
            output_stream << "#pragma once" << "\n";
            return *this;
        }

        stream& end() {
            output_stream << "\n";
            return *this;
        }

        stream& include(const std::string& path) {
            if (included_files.insert(path).second) {
                output_stream << "#include <" << path << ">\n";
            }
            return *this;
        }

        stream& namespace_begin(const std::string& name) {
            indent();
            output_stream << "namespace " << name << " {\n";
            ++indent_level;
            return *this;
        }

        stream& namespace_end() {
            --indent_level;
            indent();
            output_stream << "}\n";
            return *this;
        }

        stream& struct_begin(const std::string& struct_name) {
            indent();
            output_stream << "struct " << struct_name << " {\n";
            ++indent_level;
            return *this;
        }

        stream& struct_end(const std::string& variable_name) {
            --indent_level;
            indent();
            output_stream << "}";
            if (!variable_name.empty()) {
                output_stream << " " << variable_name;
            }
            output_stream << ";\n";
            return *this;
        }

        stream& public_() {
            --indent_level;
            indent();
            output_stream << "public:\n";
            ++indent_level;
            return *this;
        }

        stream& private_() {
            --indent_level;
            indent();
            output_stream << "private:\n";
            ++indent_level;
            return *this;
        }

        stream& line(const std::string& string) {
            indent();
            output_stream << string << "\n";
            return *this;
        }

        stream& declare_variable(const std::string& type, const std::string& name, const std::string& value = "") {
            indent();
            output_stream << type << " " << name;
            if (!value.empty()) {
                output_stream << " = " << value;
            }
            output_stream << ";\n";
            return *this;
        }

        stream& function_begin(const std::string& signature) {
            indent();
            output_stream << signature << " {\n";
            ++indent_level;
            return *this;
        }

        stream& function_end() {
            --indent_level;
            indent();
            output_stream << "}\n";
            return *this;
        }

        stream& block(const std::string& code_block) {
            std::istringstream code_stream(code_block);
            std::string line;
            while (std::getline(code_stream, line)) {
                indent();
                output_stream << line << "\n";
            }
            return *this;
        }

        std::string string() const {
            return output_stream.str();
        }

        void commit(const std::string& path) {
            std::string prefixed_path = "gctrl/" + path;
            std::filesystem::create_directories(std::filesystem::path(prefixed_path).parent_path());
            std::ofstream file(prefixed_path);
            file << output_stream.str();
            file.close();
        }
    };

    static stream code_stream;

    inline void begin(const std::string& name) {
        ui::cout << name << ui::endl;
        code_stream.begin(name);
    }

    inline void end() {
        code_stream.end();
    }

    inline void include(const std::string& path) {
        code_stream.include(path);
    }

    inline void namespace_begin(const std::string& name) {
        code_stream.namespace_begin(name);
    }

    inline void namespace_end() {
        code_stream.namespace_end();
    }

    inline void struct_begin(const std::string& struct_name) {
        code_stream.struct_begin(struct_name);
    }

    inline void struct_end(const std::string& variable_name = "") {
        code_stream.struct_end(variable_name);
    }

    inline void public_() {
        code_stream.public_();
    }

    inline void private_() {
        code_stream.private_();
    }

    inline void declare_variable(const std::string& type, const std::string& name, const std::string& value = "") {
        code_stream.declare_variable(type, name, value);
    }

    inline void line(const std::string& line) {
        code_stream.line(line);
    }

    inline void function_begin(const std::string& signature) {
        code_stream.function_begin(signature);
    }

    inline void function_end() {
        code_stream.function_end();
    }

    inline void block(const std::string& code_block) {
        code_stream.block(code_block);
    }

    inline std::string string() {
        return code_stream.string();
    }

    inline void commit(const std::string& path) {
        code_stream.commit(path);
    }

    void delete_gctrl_directory() {
        std::filesystem::path directory = "gctrl";
        if (std::filesystem::exists(directory)) {
            try {
                std::filesystem::remove_all(directory);
                std::cout << "Successfully removed directory: " << directory << std::endl;
            }
            catch (const std::filesystem::filesystem_error& e) {
                std::cerr << "Error removing directory: " << directory << std::endl;
                std::cerr << "Reason: " << e.what() << std::endl;
            }
            catch (const std::exception& e) {
                std::cerr << "Unexpected error: " << e.what() << std::endl;
            }
        }
    }

    inline void generate_gctrl_header() {
        std::string content = R"(//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#pragma once

#include <cmath>
#include <numbers>
#include <random>
#include <chrono>
#include <thread>
#include <map>
#include <unordered_map>
#include <functional>
#include <mutex>
#include <string>
#include <complex>
#include <algorithm>
#include <vector>
#include <cstdint>
#include <csignal>
#include <atomic>
#include <iostream>
#include <cstring>

namespace gctrl {
    constexpr float e = static_cast<float>(std::numbers::e);
    constexpr float log2e = static_cast<float>(std::numbers::log2e);
    constexpr float log10e = static_cast<float>(std::numbers::log10e);
    constexpr float pi = static_cast<float>(std::numbers::pi);
    constexpr float inv_pi = static_cast<float>(std::numbers::inv_pi);
    constexpr float inv_sqrtpi = static_cast<float>(std::numbers::inv_sqrtpi);
    constexpr float ln2 = static_cast<float>(std::numbers::ln2);
    constexpr float ln10 = static_cast<float>(std::numbers::ln10);
    constexpr float sqrt2 = static_cast<float>(std::numbers::sqrt2);
    constexpr float sqrt3 = static_cast<float>(std::numbers::sqrt3);
    constexpr float inv_sqrt3 = static_cast<float>(std::numbers::inv_sqrt3);
    constexpr float egamma = static_cast<float>(std::numbers::egamma);
    constexpr float phi = static_cast<float>(std::numbers::phi);

    typedef std::complex<float> complex;
    using std::clamp;
    using std::min;
    using std::max;

    class timestep {
    public:
        timestep() : last_time_(std::chrono::steady_clock::now()), delta_seconds_(0.0f) {}

        void update(std::chrono::steady_clock::time_point now) {
            auto duration = std::chrono::duration_cast<std::chrono::microseconds>(now - last_time_);
            delta_seconds_ = duration.count() / 1'000'000.0f;
        }

        void reset() {
            last_time_ = std::chrono::steady_clock::now();
            delta_seconds_ = 0.0;
        }

        float seconds() const { return delta_seconds_; }
        float milliseconds() const { return delta_seconds_ * 1000.0f; }
        float microseconds() const { return delta_seconds_ * 1'000'000.0f; }

    private:
        std::chrono::steady_clock::time_point last_time_;
        float delta_seconds_;
    };

    class timer {
    public:
        timer() : now_(std::chrono::steady_clock::now()) {}

        void update() {
            now_ = std::chrono::steady_clock::now();
            timestep_1hz.update(now_);
            timestep_10hz.update(now_);
            timestep_100hz.update(now_);
            timestep_1khz.update(now_);
            timestep_10khz.update(now_);
        }

        timestep timestep_1hz;
        timestep timestep_10hz;
        timestep timestep_100hz;
        timestep timestep_1khz;
        timestep timestep_10khz;

    private:
        std::chrono::steady_clock::time_point now_;
    };

    inline std::atomic<bool> terminate_requested = false;

    inline void handle_signal(int signal) {
        if (signal == SIGTERM || signal == SIGINT) {
            terminate_requested = true;
            std::cerr << "Signal received. Terminating process..." << std::endl;
        }
    }

    namespace binary {
        template <typename T>
        std::vector<uint8_t> serialize(const T& value) {
            std::vector<uint8_t> buffer(sizeof(T));
            std::memcpy(buffer.data(), &value, sizeof(T));
            return buffer;
        }

        template <typename T>
        T deserialize(const std::vector<uint8_t>& buffer) {
            T value;
            std::memcpy(&value, buffer.data(), sizeof(T));
            return value;
        }
    }

    namespace udp {
        class signal_registry {
        public:
            using signal_callback = std::function<void(const std::vector<uint8_t>&)>;
            void subscribe(uint64_t id, signal_callback callback);
            void notify(uint64_t id, const std::vector<uint8_t>& data);

        private:
            std::unordered_map<uint64_t, signal_callback> registry_;
            std::mutex mutex_;
        };

        class listener {
        public:
            listener(const std::string& address, uint16_t port, signal_registry& registry);
            ~listener();
            void start();
            void stop();

        private:
            signal_registry& registry_;
#ifdef _WIN32
            uintptr_t socket_fd_;
#else
            int socket_fd_;
#endif
            bool stop_;
            std::thread listener_thread_;
            void initialize_socket(const std::string& address, uint16_t port);
            void listen_for_packets();
            void close_socket();
        };

        class sender {
        public:
            sender(const std::string& address, uint16_t port);
            ~sender();
            void send(uint64_t id, const std::vector<uint8_t>& data);

        private:
            std::string address_;
            uint16_t port_;
#ifdef _WIN32
            uintptr_t socket_fd_;
#else
            int socket_fd_;
#endif
            void initialize_socket();
            void close_socket();
        };
    }
} // namespace gctrl
)";
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl.hpp");
        file << content;
        file.close();
        ui::cout << "gctrl.hpp" << ui::endl;
    }

    inline void generate_udp_driver_windows() {
        std::string content = R"(//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#include "gctrl.hpp"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <stdexcept>

#pragma comment(lib, "Ws2_32.lib")

namespace gctrl {
    namespace udp {
        void signal_registry::subscribe(uint64_t id, signal_callback callback) {
            std::lock_guard<std::mutex> lock(mutex_);
            registry_[id] = callback;
        }

        void signal_registry::notify(uint64_t id, const std::vector<uint8_t>& data) {
            std::lock_guard<std::mutex> lock(mutex_);
            if (registry_.count(id)) {
                registry_[id](data);
            }
        }

        listener::listener(const std::string& address, uint16_t port, signal_registry& registry)
            : registry_(registry), stop_(false), socket_fd_(INVALID_SOCKET) {
            initialize_socket(address, port);
        }

        listener::~listener() {
            stop();
        }

        void listener::start() {
            listener_thread_ = std::thread([this]() { listen_for_packets(); });
        }

        void listener::stop() {
            if (!stop_) {
                stop_ = true;
                closesocket(static_cast<SOCKET>(socket_fd_));
                WSACleanup();
                if (listener_thread_.joinable()) {
                    listener_thread_.join();
                }
            }
        }

        void listener::initialize_socket(const std::string& address, uint16_t port) {
            WSADATA wsa_data;
            if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {
                throw std::runtime_error("WSAStartup failed");
            }
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (static_cast<SOCKET>(socket_fd_) == INVALID_SOCKET) {
                throw std::runtime_error("Socket creation failed");
            }

            u_long mode = 1;
            if (ioctlsocket(static_cast<SOCKET>(socket_fd_), FIONBIO, &mode) != NO_ERROR) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port);
            server_addr.sin_addr.s_addr = INADDR_ANY;
            if (bind(static_cast<SOCKET>(socket_fd_), reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr)) == SOCKET_ERROR) {
                std::cerr << "Socket bind failed" << std::endl;
                throw std::runtime_error("Socket bind failed");
            }
        }

        void listener::listen_for_packets() {
            while (!stop_) {
                std::vector<uint8_t> buffer(1024);
                sockaddr_in sender_addr{};
                int sender_addr_len = sizeof(sender_addr);
                int received_bytes = recvfrom(static_cast<SOCKET>(socket_fd_), reinterpret_cast<char*>(buffer.data()), static_cast<int>(buffer.size()), 0,
                    reinterpret_cast<sockaddr*>(&sender_addr), &sender_addr_len);
                if (received_bytes > 0) {
                    buffer.resize(received_bytes);
                    if (buffer.size() >= sizeof(uint64_t)) {
                        uint64_t id;
                        std::memcpy(&id, buffer.data(), sizeof(uint64_t));
                        registry_.notify(id, { buffer.begin() + sizeof(uint64_t), buffer.end() });
                    }
                }
                else if (WSAGetLastError() != WSAEWOULDBLOCK) {
                    std::cerr << "recvfrom error: " << WSAGetLastError() << std::endl;
                }

                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        }

        void listener::close_socket() {
            if (static_cast<SOCKET>(socket_fd_) != INVALID_SOCKET) {
                closesocket(static_cast<SOCKET>(socket_fd_));
                WSACleanup();
            }
        }

        sender::sender(const std::string& address, uint16_t port)
            : address_(address), port_(port), socket_fd_(INVALID_SOCKET) {
            initialize_socket();
        }

        void sender::initialize_socket() {
            WSADATA wsa_data;
            if (WSAStartup(MAKEWORD(2, 2), &wsa_data) != 0) {
                throw std::runtime_error("WSAStartup failed");
            }
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (static_cast<SOCKET>(socket_fd_) == INVALID_SOCKET) {
                throw std::runtime_error("Socket creation failed");
            }

            u_long mode = 1;
            if (ioctlsocket(static_cast<SOCKET>(socket_fd_), FIONBIO, &mode) != NO_ERROR) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }
        }

        void sender::send(uint64_t id, const std::vector<uint8_t>& data) {
            std::vector<uint8_t> packet(sizeof(id) + data.size());
            std::memcpy(packet.data(), &id, sizeof(id));
            std::memcpy(packet.data() + sizeof(id), data.data(), data.size());

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port_);
            InetPtonA(AF_INET, address_.c_str(), &server_addr.sin_addr);

            int result = sendto(static_cast<SOCKET>(socket_fd_), reinterpret_cast<const char*>(packet.data()), static_cast<int>(packet.size()), 0,
                reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr));
            if (result == SOCKET_ERROR && WSAGetLastError() != WSAEWOULDBLOCK) {
                std::cerr << "sendto error: " << WSAGetLastError() << std::endl;
            }
        }

        void sender::close_socket() {
            if (static_cast<SOCKET>(socket_fd_) != INVALID_SOCKET) {
                closesocket(static_cast<SOCKET>(socket_fd_));
                WSACleanup();
            }
        }

        sender::~sender() {
            close_socket();
        }
    }
}
)";
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl_udp_windows.cpp");
        file << content;
        file.close();
        ui::cout << "gctrl_udp_windows.cpp" << ui::endl;
    }

    inline void generate_udp_driver_linux() {
        std::string content = R"(//
// Generated by General Controls Engine.
// License: GNU General Public License v3.0 or later.
//
// Copyright (C) 2024 Daher Alfawares
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
// Contact Information: www.gctrl.org
//

#include "gctrl.hpp"
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdexcept>
#include <cerrno>

namespace gctrl {
    namespace udp {
        void signal_registry::subscribe(uint64_t id, signal_callback callback) {
            std::lock_guard<std::mutex> lock(mutex_);
            registry_[id] = callback;
        }

        void signal_registry::notify(uint64_t id, const std::vector<uint8_t>& data) {
            std::lock_guard<std::mutex> lock(mutex_);
            if (registry_.count(id)) {
                registry_[id](data);
            }
        }

        listener::listener(const std::string& address, uint16_t port, signal_registry& registry)
            : registry_(registry), stop_(false), socket_fd_(-1) {
            initialize_socket(address, port);
        }

        listener::~listener() {
            stop();
        }

        void listener::start() {
            listener_thread_ = std::thread([this]() { listen_for_packets(); });
        }

        void listener::stop() {
            if (!stop_) {
                stop_ = true;
                close_socket();
                if (listener_thread_.joinable()) {
                    listener_thread_.join();
                }
            }
        }

        void listener::initialize_socket(const std::string& address, uint16_t port) {
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (socket_fd_ < 0) {
                throw std::runtime_error("Socket creation failed");
            }

            int flags = fcntl(socket_fd_, F_GETFL, 0);
            if (flags < 0 || fcntl(socket_fd_, F_SETFL, flags | O_NONBLOCK) < 0) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port);
            server_addr.sin_addr.s_addr = INADDR_ANY;
            if (bind(socket_fd_, reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr)) < 0) {
                std::cerr << "Socket bind failed: " << strerror(errno) << std::endl;
                throw std::runtime_error("Socket bind failed");
            }
        }

        void listener::listen_for_packets() {
            while (!stop_) {
                std::vector<uint8_t> buffer(1024);
                sockaddr_in sender_addr{};
                socklen_t sender_addr_len = sizeof(sender_addr);
                ssize_t received_bytes = recvfrom(socket_fd_, buffer.data(), buffer.size(), 0,
                    reinterpret_cast<sockaddr*>(&sender_addr), &sender_addr_len);
                if (received_bytes > 0) {
                    buffer.resize(received_bytes);
                    if (buffer.size() >= sizeof(uint64_t)) {
                        uint64_t id;
                        std::memcpy(&id, buffer.data(), sizeof(uint64_t));
                        registry_.notify(id, { buffer.begin() + sizeof(uint64_t), buffer.end() });
                    }
                }
                else if (received_bytes < 0 && errno != EAGAIN && errno != EWOULDBLOCK) {
                    std::cerr << "recvfrom error: " << strerror(errno) << std::endl;
                }

                std::this_thread::sleep_for(std::chrono::milliseconds(10));
            }
        }

        void listener::close_socket() {
            if (socket_fd_ >= 0) {
                close(socket_fd_);
                socket_fd_ = -1;
            }
        }

        sender::sender(const std::string& address, uint16_t port)
            : address_(address), port_(port), socket_fd_(-1) {
            initialize_socket();
        }

        void sender::initialize_socket() {
            socket_fd_ = socket(AF_INET, SOCK_DGRAM, 0);
            if (socket_fd_ < 0) {
                throw std::runtime_error("Socket creation failed");
            }

            int flags = fcntl(socket_fd_, F_GETFL, 0);
            if (flags < 0 || fcntl(socket_fd_, F_SETFL, flags | O_NONBLOCK) < 0) {
                throw std::runtime_error("Failed to set non-blocking mode");
            }
        }

        void sender::send(uint64_t id, const std::vector<uint8_t>& data) {
            std::vector<uint8_t> packet(sizeof(id) + data.size());
            std::memcpy(packet.data(), &id, sizeof(id));
            std::memcpy(packet.data() + sizeof(id), data.data(), data.size());

            sockaddr_in server_addr{};
            server_addr.sin_family = AF_INET;
            server_addr.sin_port = htons(port_);
            inet_pton(AF_INET, address_.c_str(), &server_addr.sin_addr);

            ssize_t result = sendto(socket_fd_, packet.data(), packet.size(), 0,
                reinterpret_cast<sockaddr*>(&server_addr), sizeof(server_addr));
            if (result < 0 && errno != EAGAIN && errno != EWOULDBLOCK) {
                std::cerr << "sendto error: " << strerror(errno) << std::endl;
            }
        }

        void sender::close_socket() {
            if (socket_fd_ >= 0) {
                close(socket_fd_);
                socket_fd_ = -1;
            }
        }

        sender::~sender() {
            close_socket();
        }
    }
}
)";
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/gctrl_udp_linux.cpp");
        file << content;
        file.close();
        ui::cout << "gctrl_udp_linux.cpp" << ui::endl;
    }

    inline void generate_cmake(const std::string& machine_name) {
        std::stringstream ss;
        ss << R"(#
# Generated by General Controls Engine.
# License: GNU General Public License v3.0 or later.
#
# Copyright (C) 2024 Daher Alfawares
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Contact Information: www.gctrl.org
#

cmake_minimum_required(VERSION 3.15)
project()" << machine_name << R"( LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(WIN32)
    set(PLATFORM_SOURCES gctrl_udp_windows.cpp)
    set(PLATFORM_LIBS ws2_32)
else()
    set(PLATFORM_SOURCES gctrl_udp_linux.cpp)
    set(PLATFORM_LIBS pthread)
endif()

add_executable()" << machine_name << R"(
    ../)" << machine_name << R"(.cpp
    ${PLATFORM_SOURCES}
)

target_link_libraries()" << machine_name << R"( PRIVATE ${PLATFORM_LIBS})
target_include_directories()" << machine_name << R"( PRIVATE
    ${CMAKE_SOURCE_DIR}
    ${CMAKE_SOURCE_DIR}/..
)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set_target_properties()" << machine_name << R"( PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
)

if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_compile_options()" << machine_name << R"( PRIVATE
        $<$<CONFIG:Debug>:-g>
        $<$<CONFIG:Release>:-O2 -DNDEBUG>
    )
endif()
)";
        std::filesystem::create_directories("gctrl");
        std::ofstream file("gctrl/CMakeLists.txt");
        file << ss.str();
        file.close();
        ui::cout << "CMakeLists.txt" << ui::endl;
    }

    inline void generate_boilerplate(const std::string& machine_name) {
        generate_gctrl_header();
        generate_udp_driver_windows();
        generate_udp_driver_linux();
        generate_cmake(machine_name);
    }
}
